name = "toml_slicer"
description = "Edit TOML files directly without parsing"
version = "0.1.2"
licenses = "MIT"
tags = ["toml", "edition"]

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
website = "https://github.com/mosteo/toml_slicer"

[[depends-on]]
aaa = "~0.2.4|~0.3"
